[build]
  command = "npm start"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/fridge"
  status = 200

[template.environment]
  REACT_APP_ENDPOINT = "https://www.fridgebuddy.tech"
  REACT_APP_PROJECT = "636f3bb94af04e46d7b1"
  REACT_APP_COLLECTION_ID = "636fc0c65d8890e04b5f"
  REACT_APP_DATABASE_ID = "636fbecba5326c783b1c"